(function () {
    const fallbackExpectancy = 72;

    const countries = [
        { name: 'Австралия', expectancy: 83 },
        { name: 'Австрия', expectancy: 82 },
        { name: 'Азербайджан', expectancy: 73 },
        { name: 'Албания', expectancy: 78 },
        { name: 'Алжир', expectancy: 77 },
        { name: 'Ангола', expectancy: 62 },
        { name: 'Андорра', expectancy: 84 },
        { name: 'Антигуа и Барбуда', expectancy: 78 },
        { name: 'Аргентина', expectancy: 77 },
        { name: 'Армения', expectancy: 75 },
        { name: 'Афганистан', expectancy: 65 },
        { name: 'Багамы', expectancy: 73 },
        { name: 'Бангладеш', expectancy: 73 },
        { name: 'Барбадос', expectancy: 79 },
        { name: 'Бахрейн', expectancy: 78 },
        { name: 'Беларусь', expectancy: 74 },
        { name: 'Белиз', expectancy: 75 },
        { name: 'Бельгия', expectancy: 82 },
        { name: 'Бенин', expectancy: 63 },
        { name: 'Болгария', expectancy: 75 },
        { name: 'Боливия', expectancy: 72 },
        { name: 'Босния и Герцеговина', expectancy: 77 },
        { name: 'Ботсвана', expectancy: 70 },
        { name: 'Бразилия', expectancy: 76 },
        { name: 'Бруней', expectancy: 78 },
        { name: 'Буркина-Фасо', expectancy: 61 },
        { name: 'Бурунди', expectancy: 62 },
        { name: 'Бутан', expectancy: 72 },
        { name: 'Вануату', expectancy: 70 },
        { name: 'Ватикан', expectancy: 84 },
        { name: 'Великобритания', expectancy: 81 },
        { name: 'Венгрия', expectancy: 76 },
        { name: 'Венесуэла', expectancy: 72 },
        { name: 'Вьетнам', expectancy: 75 },
        { name: 'Габон', expectancy: 67 },
        { name: 'Гаити', expectancy: 64 },
        { name: 'Гайана', expectancy: 69 },
        { name: 'Гамбия', expectancy: 62 },
        { name: 'Гана', expectancy: 65 },
        { name: 'Гватемала', expectancy: 73 },
        { name: 'Гвинея', expectancy: 63 },
        { name: 'Гвинея-Бисау', expectancy: 60 },
        { name: 'Германия', expectancy: 81 },
        { name: 'Гондурас', expectancy: 74 },
        { name: 'Гренада', expectancy: 72 },
        { name: 'Греция', expectancy: 82 },
        { name: 'Грузия', expectancy: 74 },
        { name: 'Дания', expectancy: 81 },
        { name: 'Джибути', expectancy: 67 },
        { name: 'Доминика', expectancy: 77 },
        { name: 'Доминиканская Республика', expectancy: 74 },
        { name: 'ДР Конго', expectancy: 61 },
        { name: 'Египет', expectancy: 71 },
        { name: 'Замбия', expectancy: 63 },
        { name: 'Зимбабве', expectancy: 62 },
        { name: 'Израиль', expectancy: 83 },
        { name: 'Индия', expectancy: 70 },
        { name: 'Индонезия', expectancy: 72 },
        { name: 'Иордания', expectancy: 74 },
        { name: 'Ирак', expectancy: 70 },
        { name: 'Иран', expectancy: 76 },
        { name: 'Ирландия', expectancy: 82 },
        { name: 'Исландия', expectancy: 83 },
        { name: 'Испания', expectancy: 84 },
        { name: 'Италия', expectancy: 83 },
        { name: 'Йемен', expectancy: 66 },
        { name: 'Кабо-Верде', expectancy: 73 },
        { name: 'Казахстан', expectancy: 73 },
        { name: 'Камбоджа', expectancy: 70 },
        { name: 'Камерун', expectancy: 61 },
        { name: 'Канада', expectancy: 82 },
        { name: 'Катар', expectancy: 80 },
        { name: 'Кения', expectancy: 66 },
        { name: 'Кипр', expectancy: 82 },
        { name: 'Киргизия', expectancy: 71 },
        { name: 'Кирибати', expectancy: 68 },
        { name: 'Китай', expectancy: 78 },
        { name: 'КНДР', expectancy: 72 },
        { name: 'Колумбия', expectancy: 77 },
        { name: 'Коморы', expectancy: 65 },
        { name: 'Коста-Рика', expectancy: 80 },
        { name: 'Кот-д’Ивуар', expectancy: 61 },
        { name: 'Куба', expectancy: 79 },
        { name: 'Кувейт', expectancy: 78 },
        { name: 'Лаос', expectancy: 68 },
        { name: 'Латвия', expectancy: 75 },
        { name: 'Лесото', expectancy: 55 },
        { name: 'Ливан', expectancy: 78 },
        { name: 'Ливия', expectancy: 73 },
        { name: 'Литва', expectancy: 76 },
        { name: 'Лихтенштейн', expectancy: 84 },
        { name: 'Люксембург', expectancy: 83 },
        { name: 'Маврикий', expectancy: 76 },
        { name: 'Мавритания', expectancy: 65 },
        { name: 'Мадагаскар', expectancy: 67 },
        { name: 'Малави', expectancy: 65 },
        { name: 'Малайзия', expectancy: 76 },
        { name: 'Мали', expectancy: 60 },
        { name: 'Мальдивы', expectancy: 79 },
        { name: 'Мальта', expectancy: 83 },
        { name: 'Марокко', expectancy: 76 },
        { name: 'Маршалловы Острова', expectancy: 73 },
        { name: 'Мексика', expectancy: 75 },
        { name: 'Микронезия', expectancy: 68 },
        { name: 'Мозамбик', expectancy: 61 },
        { name: 'Молдова', expectancy: 72 },
        { name: 'Монако', expectancy: 85 },
        { name: 'Монголия', expectancy: 70 },
        { name: 'Мьянма', expectancy: 67 },
        { name: 'Намибия', expectancy: 65 },
        { name: 'Науру', expectancy: 67 },
        { name: 'Непал', expectancy: 70 },
        { name: 'Нигер', expectancy: 62 },
        { name: 'Нигерия', expectancy: 55 },
        { name: 'Нидерланды', expectancy: 82 },
        { name: 'Никарагуа', expectancy: 75 },
        { name: 'Новая Зеландия', expectancy: 82 },
        { name: 'Норвегия', expectancy: 83 },
        { name: 'ОАЭ', expectancy: 79 },
        { name: 'Оман', expectancy: 78 },
        { name: 'Пакистан', expectancy: 67 },
        { name: 'Палау', expectancy: 73 },
        { name: 'Палестина', expectancy: 73 },
        { name: 'Панама', expectancy: 79 },
        { name: 'Папуа — Новая Гвинея', expectancy: 65 },
        { name: 'Парагвай', expectancy: 74 },
        { name: 'Перу', expectancy: 77 },
        { name: 'Польша', expectancy: 78 },
        { name: 'Португалия', expectancy: 82 },
        { name: 'Россия', expectancy: 72 },
        { name: 'Руанда', expectancy: 68 },
        { name: 'Румыния', expectancy: 76 },
        { name: 'Сальвадор', expectancy: 74 },
        { name: 'Самоа', expectancy: 73 },
        { name: 'Сан-Марино', expectancy: 84 },
        { name: 'Сан-Томе и Принсипи', expectancy: 68 },
        { name: 'Саудовская Аравия', expectancy: 76 },
        { name: 'Северная Македония', expectancy: 76 },
        { name: 'Сейшелы', expectancy: 77 },
        { name: 'Сенегал', expectancy: 67 },
        { name: 'Сент-Винсент и Гренадины', expectancy: 73 },
        { name: 'Сент-Китс и Невис', expectancy: 75 },
        { name: 'Сент-Люсия', expectancy: 76 },
        { name: 'Сербия', expectancy: 75 },
        { name: 'Сингапур', expectancy: 84 },
        { name: 'Сирия', expectancy: 69 },
        { name: 'Словакия', expectancy: 77 },
        { name: 'Словения', expectancy: 82 },
        { name: 'Соломоновы Острова', expectancy: 71 },
        { name: 'Сомали', expectancy: 57 },
        { name: 'Судан', expectancy: 65 },
        { name: 'Суринам', expectancy: 72 },
        { name: 'США', expectancy: 78 },
        { name: 'Сьерра-Леоне', expectancy: 55 },
        { name: 'Таджикистан', expectancy: 70 },
        { name: 'Таиланд', expectancy: 77 },
        { name: 'Тайвань', expectancy: 81 },
        { name: 'Танзания', expectancy: 66 },
        { name: 'Того', expectancy: 62 },
        { name: 'Тонга', expectancy: 70 },
        { name: 'Тринидад и Тобаго', expectancy: 74 },
        { name: 'Тувалу', expectancy: 69 },
        { name: 'Тунис', expectancy: 77 },
        { name: 'Туркменистан', expectancy: 68 },
        { name: 'Турция', expectancy: 78 },
        { name: 'Уганда', expectancy: 64 },
        { name: 'Узбекистан', expectancy: 72 },
        { name: 'Украина', expectancy: 72 },
        { name: 'Уругвай', expectancy: 78 },
        { name: 'Фиджи', expectancy: 68 },
        { name: 'Филиппины', expectancy: 71 },
        { name: 'Финляндия', expectancy: 82 },
        { name: 'Франция', expectancy: 83 },
        { name: 'Хорватия', expectancy: 78 },
        { name: 'ЦАР', expectancy: 54 },
        { name: 'Чад', expectancy: 54 },
        { name: 'Черногория', expectancy: 77 },
        { name: 'Чехия', expectancy: 79 },
        { name: 'Чили', expectancy: 80 },
        { name: 'Швейцария', expectancy: 84 },
        { name: 'Швеция', expectancy: 83 },
        { name: 'Шри-Ланка', expectancy: 77 },
        { name: 'Эквадор', expectancy: 77 },
        { name: 'Экваториальная Гвинея', expectancy: 59 },
        { name: 'Эритрея', expectancy: 67 },
        { name: 'Эсватини', expectancy: 60 },
        { name: 'Эстония', expectancy: 78 },
        { name: 'Эфиопия', expectancy: 66 },
        { name: 'ЮАР', expectancy: 65 },
        { name: 'Южная Корея', expectancy: 83 },
        { name: 'Южный Судан', expectancy: 57 },
        { name: 'Ямайка', expectancy: 75 },
        { name: 'Япония', expectancy: 85 }
    ];

    const lookup = new Map(
        countries.map((country) => [country.name.toLowerCase(), country.expectancy])
    );

    function getCountryExpectancy(name) {
        if (!name) {
            return fallbackExpectancy;
        }

        const normalized = String(name).trim().toLowerCase();
        if (!normalized) {
            return fallbackExpectancy;
        }

        return lookup.get(normalized) ?? fallbackExpectancy;
    }

    window.LifeTestConfig = Object.assign(window.LifeTestConfig || {}, {
        countries,
        fallbackExpectancy,
        getCountryExpectancy
    });
})();
